#!/usr/bin/env python3
"""Generate the canonical checked-in API contract and human endpoint index."""

from __future__ import annotations

import argparse
import copy
import json
import os
import tempfile
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

# Schema generation must never inherit a deployment database URL. Importing the
# app does not enter its lifespan, but binding its modules to disposable SQLite
# keeps this command safe even when it is run on the production host.
_SCHEMA_DB = Path(tempfile.gettempdir()) / "openterminalui_api_reference.db"
os.environ["DATABASE_URL"] = f"sqlite+aiosqlite:///{_SCHEMA_DB}"
os.environ["OPENTERMINALUI_INSTRUMENT_AUTOSEED"] = "0"

from backend.main import app
from backend.openapi_contract import HTTP_METHODS


ROOT = Path(__file__).resolve().parents[1]
INVENTORY_PATH = ROOT / "docs" / "surface-inventory.json"
OPENAPI_PATH = ROOT / "docs" / "openapi.json"
REFERENCE_PATH = ROOT / "docs" / "API_REFERENCE.md"

STATE_MEANINGS = {
    "supported": "Stable v1 product contract; upstream data can still degrade honestly.",
    "configuration-gated": "Useful only in a supported market or with documented provider configuration.",
    "experimental": "Retained for evaluation, outside the stable v1 promise.",
    "hidden": "Compatibility API retained but not advertised in primary navigation.",
    "remove": "Scheduled for removal after consumer and regression verification.",
}


def _operations(schema: dict[str, Any]):
    for path in sorted(schema["paths"]):
        path_item = schema["paths"][path]
        for method in sorted(HTTP_METHODS):
            operation = path_item.get(method)
            if isinstance(operation, dict):
                yield path, method, operation


def _add_feature_states(
    schema: dict[str, Any], family_states: dict[str, str]
) -> None:
    schema["x-openterminalui-family-states"] = dict(sorted(family_states.items()))
    for _path, _method, operation in _operations(schema):
        tags = operation.get("tags") or ["untagged"]
        missing = [tag for tag in tags if tag not in family_states]
        if missing:
            raise ValueError(f"unclassified OpenAPI tags: {missing}")
        operation["x-openterminalui-feature-state"] = {
            tag: family_states[tag] for tag in tags
        }


def _auth_label(operation: dict[str, Any]) -> str:
    auth = operation["x-openterminalui-auth"]
    if auth["scheme"] == "api-key":
        return f"API key ({auth['permission']})"
    if auth["scheme"] == "bearer":
        return "Bearer token"
    return "None"


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _render_markdown(
    schema: dict[str, Any], family_states: dict[str, str]
) -> str:
    grouped: dict[str, list[tuple[str, str, dict[str, Any]]]] = defaultdict(list)
    auth_counts: Counter[str] = Counter()
    operation_count = 0
    for path, method, operation in _operations(schema):
        primary_family = (operation.get("tags") or ["untagged"])[0]
        grouped[primary_family].append((path, method, operation))
        auth_counts[_auth_label(operation)] += 1
        operation_count += 1

    state_counts = Counter(family_states.values())
    lines = [
        "# API reference",
        "",
        "> Generated by `scripts/generate_api_reference.py`; do not edit by hand.",
        "> Run the generator after changing routes, schemas, authentication, or",
        "> `docs/surface-inventory.json`.",
        "",
        "This is the canonical repository snapshot of the backend API. The complete",
        "request and response schemas are in [`openapi.json`](openapi.json); a running",
        "backend serves the same schemas interactively at `/docs` and as JSON at",
        "`/openapi.json`. Feature state describes the product promise, not whether an",
        "upstream provider is currently healthy; runtime degradation and configuration",
        "requirements are documented in [`wiki/Limitations.md`](wiki/Limitations.md).",
        "",
        "## Contract summary",
        "",
        f"- **{operation_count} operations** across **{len(schema['paths'])} paths** and **{len(family_states)} families**.",
        f"- Authentication: **{auth_counts['Bearer token']} bearer**, **{auth_counts['API key (read)']} read API-key**, **{auth_counts['API key (read_write)']} write API-key**, **{auth_counts['None']} unauthenticated** operations.",
        "- API keys are created and revoked by an authenticated user under `/api/settings/api-keys`.",
        "- `read_write` is required for `PUT /api/v1/notes/external`; market-data automation endpoints require `read` or `read_write`.",
        "",
        "## Feature-state vocabulary",
        "",
        "| State | Families | Meaning |",
        "|---|---:|---|",
    ]
    for state in STATE_MEANINGS:
        lines.append(
            f"| `{state}` | {state_counts[state]} | {_cell(STATE_MEANINGS[state])} |"
        )

    lines.extend(
        [
            "",
            "## Family matrix",
            "",
            "| Family | State | Operations |",
            "|---|---|---:|",
        ]
    )
    for family, state in sorted(family_states.items()):
        lines.append(f"| `{family}` | `{state}` | {len(grouped[family])} |")

    lines.extend(["", "## Endpoint catalog", ""])
    for family, state in sorted(family_states.items()):
        lines.extend(
            [
                f"### `{family}`",
                "",
                f"State: **{state}**",
                "",
                "| Method | Path | Authentication | Summary |",
                "|---|---|---|---|",
            ]
        )
        for path, method, operation in grouped[family]:
            summary = operation.get("summary") or operation.get("operationId") or "—"
            lines.append(
                f"| `{method.upper()}` | `{_cell(path)}` | {_auth_label(operation)} | {_cell(summary)} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def generate() -> dict[Path, str]:
    inventory = json.loads(INVENTORY_PATH.read_text(encoding="utf-8"))
    family_states: dict[str, str] = inventory["api_families"]
    schema = copy.deepcopy(app.openapi())
    _add_feature_states(schema, family_states)
    openapi_text = json.dumps(schema, indent=2, sort_keys=True) + "\n"
    return {
        OPENAPI_PATH: openapi_text,
        REFERENCE_PATH: _render_markdown(schema, family_states),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if checked-in API artifacts differ from the generated contract",
    )
    args = parser.parse_args()

    generated = generate()
    drifted: list[Path] = []
    for path, content in generated.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                drifted.append(path)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")

    if drifted:
        for path in drifted:
            print(f"stale generated API artifact: {path.relative_to(ROOT)}")
        print("run: PYTHONPATH=. python scripts/generate_api_reference.py")
        return 1
    if args.check:
        print("generated API reference is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
